### ISSUE TITLE
Unsupported Protocol Version

### ISSUE THREAD

**Issue by theshapguy** [zemanel/openshift-sentry-quickstart#7]
Client configuration:
  servers        : [Removed by me] 
  project        : [Removed by me] 
  public_key     : [Removed by me] 
  secret_key     : [Removed by me] 

Sending a test message... success!
Event ID was '6b2bceced9ed4a0dbd9e6900b685036a'
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Unable to capture event: Client/server version mismatch: Unsupported protocol version (5)
Failed to submit message: u'This is a test message generated using `raven test`'

**Comment by j1fig** [comment]
You can see the exception being raised here - https://github.com/getsentry/sentry/blob/master/src/sentry/web/api.py

This is due to raven(client) and sentry(server) version mismatch - and therefore the used protocol.

This quickstart uses sentry=6.2.1.

Depending on your raven version you might need a newer version of sentry - see http://raven.readthedocs.org/en/latest/.

For using raven 5.1.1. you'd need sentry 6.4.

**Comment by zemanel** [comment]
@joaonvfigueiredo cool thanks, i'll take a look soon (haven't picked up on Openshift in quite a while), meanwhile i'll give you RW perms to the repo if you have a fix.

**Comment by j1fig** [comment]
@shapath , @zemanel I never did post a fix to this since it's more version management related and depends on your sentry client (raven) version.

Maybe post this info in the README as a Note/Warning in order for people using this to check compatibility of their Raven versions ;)

**Comment by zemanel** [comment]
@joaonvfigueiredo got it. i'd like to pickup and re-test this project again soon and update the README.

**Comment by q10** [comment]
Please update the README since I am having a lot of trouble with getting a newer version of Sentry running on Openshift

**Comment by zemanel** [comment]
Things seem to have changed quite a bit since i last used this, will take a look asap.

**Comment by q10** [comment]
Thanks; really appreciate it!

**Comment by q10** [comment]
Hey zemanel, did you get a chance to update this cartridge yet?

**Comment by zemanel** [comment]
Yes i did, work in progress will have more news end of today

**Comment by zemanel** [comment]
@q10 still taking a look at this, have some issues on my test Openshift account(s) and project code is severely outdated :-)

**Comment by q10** [comment]
Thanks for keeping me updated on this; I had tons of trouble with setting it up as well

**Comment by jimpriest** [comment]
I'm running into this issue as well - Raven 5.20.0 and Sentry 6.2.1

What's the correct Raven version I should try with 6.2.1?

**Comment by Jossymolina** [comment]
{"code":5,"message":"Unsupported protocol version"}

**Comment by Jossymolina** [comment]
Me conecto al servidor con Angula y no tengo problemas,
mi problema es cuando me conecto con ionic.

**Comment by Jossymolina** [comment]
inicio:1 Access to XMLHttpRequest at 'http://localhost:3001/socket.io/?EIO=3&transport=polling&t=NVvYJY5' from origin 'http://localhost:8100' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'allowedOrigins'.
zone-evergreen.js:2845 GET http://localhost:3001/socket.io/?EIO=3&transport=polling&t=NVvYJY5 net::ERR_FAILED
scheduleTask @ zone-evergreen.js:2845
scheduleTask @ zone-evergreen.js:385
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMacroTask @ zone-evergreen.js:233
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1134
(anonymous) @ zone-evergreen.js:2878
proto.<computed> @ zone-evergreen.js:1449
push.K/+X.Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
push.K/+X.XHR.request @ polling-xhr.js:96
push.K/+X.XHR.doPoll @ polling-xhr.js:126
push.3exg.Polling.poll @ polling.js:118
push.3exg.Polling.doOpen @ polling.js:63
push.0zaL.Transport.open @ transport.js:84
push.uKDP.Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
push.wlXU.Manager.open.Manager.connect @ manager.js:226
Manager @ manager.js:69
Manager @ manager.js:37
lookup @ index.js:60
WrappedSocket @ ngx-socket-io.js:24
SocketFactory @ ngx-socket-io.js:80
factory @ core.js:11469
hydrate @ core.js:11380
get @ core.js:11201
get @ core.js:25276
get @ core.js:11212
get @ core.js:25276
get @ core.js:24990
lookupTokenUsingModuleInjector @ core.js:3327
getOrCreateInjectable @ core.js:3439
ɵɵdirectiveInject @ core.js:14650
InicioPage_Factory @ ɵfac.js? [sm]:1
getNodeInjectable @ core.js:3534
instantiateRootComponent @ core.js:10084
createRootComponent @ core.js:12396
create @ core.js:25079
createComponent @ core.js:23119
activateWith @ ionic-angular.js:2924
activateRoutes @ router.js:2129
(anonymous) @ router.js:2080
activateChildRoutes @ router.js:2079
activateRoutes @ router.js:2136
(anonymous) @ router.js:2080
activateChildRoutes @ router.js:2079
activate @ router.js:2005
(anonymous) @ router.js:1990
_next @ map.js:29
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ map.js:16
subscribe @ Observable.js:23
innerSubscribe @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
innerSubscribe @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
_complete @ takeLast.js:52
complete @ Subscriber.js:61
_complete @ tap.js:66
complete @ Subscriber.js:61
_complete @ mergeMap.js:65
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:5
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
call @ takeLast.js:22
subscribe @ Observable.js:23
call @ mergeMap.js:19
subscribe @ Observable.js:23
innerSubscribe @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
innerSubscribe @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ tap.js:16
subscribe @ Observable.js:23
call @ switchMap.js:15
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
innerSubscribe @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_complete @ defaultIfEmpty.js:25
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ mergeMap.js:65
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:5
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ take.js:22
subscribe @ Observable.js:23
call @ defaultIfEmpty.js:10
subscribe @ Observable.js:23
innerSubscribe @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
_complete @ defaultIfEmpty.js:25
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ mergeMap.js:65
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:5
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ take.js:22
subscribe @ Observable.js:23
call @ defaultIfEmpty.js:10
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
resolvePromise @ zone-evergreen.js:785
(anonymous) @ zone-evergreen.js:705
webpackJsonpCallback @ bootstrap:25
(anonymous) @ vistas-inicio-inicio-module.js:1
Show 170 more frames

**Comment by Jossymolina** [comment]
var io = require('socket.io')(http,{
  cors: {
    origin: "*",
 
    methods: ["GET", "POST"]
  }
});
